networks:
  default:
    driver: bridge
    name: roboshop
volumes:
  mongodb:
  redis:
  mysql:
  rabbitmq: 
services:
  mongodb:
    image: harshatejaadduri/mongodb:v2
    container_name: mongodb
    volumes:
    - mongodb:/data/db
  catalogue:
    image: harshatejaadduri/catalogue:v2
    container_name: catalogue
    depends_on:
    - mongodb
  redis:
    image: redis:7-alpine
    container_name: redis
    volumes:
    - redis:/data
  user:
    image: harshatejaadduri/user:v2
    container_name: user
    depends_on:
    - redis
    - mongodb
  cart:
    image: harshatejaadduri/cart:v2
    container_name: cart
    depends_on:
    - catalogue
    - redis
  mysql:
    image: harshatejaadduri/mysql:v2
    container_name: mysql
    volumes:
    - mysql:/var/lib/mysql
    - ./init-scripts:/docker-entrypoint-initdb.d
  shipping:
    image: harshatejaadduri/shipping:v2
    container_name: shipping
    depends_on:
    - mysql
    - cart
    ports:
      - 8080:8080
    volumes:
      - ./m2:/root/.m2
  rabbitmq:
    image: rabbitmq:3-alpine
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: roboshop
      RABBITMQ_DEFAULT_PASS: roboshop123
    volumes:
    - rabbitmq:/var/lib/rabbitmq
  payment:
    image: harshatejaadduri/payment:v2
    container_name: payment
    environment:
      CART_HOST: cart
      CART_PORT: 8080
      USER_HOST: user
      USER_PORT: 8080
      AMQP_HOST: rabbitmq
      AMQP_USER: roboshop
      AMQP_PASS: roboshop123
    depends_on:
    - rabbitmq
    - cart
    - user
  frontend:
    image: harshatejaadduri/frontend:v2
    container_name: frontend
    ports:
    - "80:80"
    depends_on:
    - catalogue
    - user
    - cart
    - shipping
    - payment
      
